[files]
extend-exclude = [
    "**/*.wit",
    "**/*.wit.go",
    "**/mermaid.min.js",
    "**/mermaid-init.js",
    "**/bindings.rs",
]

[default.extend-words]
# Part of "Wassette" pronunciation guide
Wass = "Wass"
# CSS variable name in docs/theme/toc.css
existant = "existant"
